
services:
  sarlu:
    # uncomment this and use for dev mode direct build
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    # use hub image for (production)
    image: jeanfelixsagno/kf-sarlu:1.0.0

    container_name: sarlu
    volumes:
      - sarlu_data:/app
    restart: unless-stopped

  nginx:
    image: nginx:1.24-alpine
    container_name: sarlu-nginx
    ports:
      - "9000:80"
    volumes:
      - sarlu_data:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - sarlu

volumes:
  sarlu_data:
