version: '3.8'

services:
  sarlu:
    # use build for dev
    build:
      context: .
      dockerfile: Dockerfile

    # image: your_dockerhub_username/react-app:latest

    container_name: sarlu
    ports:
      - "8089:80"
    volumes:
      - sarlu_data:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  sarlu_data:
